packages:
  - packages/**

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - oxc-resolver

catalogs:
  dev:
    tsdown: ^0.22.3
    typescript: ^5.9.3
  prod:
    citty: ^0.2.2
    jiti: ^2.7.0
    pathe: ^2.0.3
    pkg-types: ^2.3.1
    tinyglobby: ^0.2.17
