name: ci

on:
  push:
    branches:
      - beta
  pull_request:
    branches:
      - beta

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.3
      - uses: pnpm/action-setup@v4.4.0
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Typecheck
        run: pnpm typecheck

  lint:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.3
      - uses: pnpm/action-setup@v4.4.0
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint
