name: Publish & Release

on:
  push:
    branches:
      - beta

permissions:
  contents: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'Version Packages')"
    steps:
      - uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4.2.0

      - uses: actions/setup-node@v6.1.0
        with:
          node-version: lts/*
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish to NPM
        uses: changesets/action@v1.5.3
        with:
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
